name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cd
      run: cd Wordler/
    - name: wordler
      run: ./wordler
    - name: make
      run: make
