#adds CI for building the code automatically
#Im not sure what went wrong here, but i think line 19 is the issue
name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y build-essential
      - name: Compile C++ 2017
        run: make 
