ame: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C++ 2017
        run: g++ -std=c++11 -Wfatal-errors main.cpp dictionary.cpp -o wordler


